### ISSUE TITLE
Spring Naming Strategy works unexpectedly for column with single char in the end

### ISSUE THREAD

**Issue by daggerok** [spring-projects/spring-data-jpa#2450]
Hello Spring Data team! Off topic: You are awesome!

We are using `spring-data-jpa` with spring naming strategy and we found bug when its generating a column name for entity with property ends with single char, like for example:
- `myTypeA` which I'm expecting should result into`my_type_a`
- or `myTypeB` => `my_type_b`

```yaml
spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
```

Spring Data JPA Entity

```kotlin
@Entity
data class GamingActivityReport(

    @Id
    @GeneratedValue(strategy = IDENTITY)
    val id: Long? = null,

    // @Column(name = "my_type_a") // when @Column annotation is commented, column will be resulted in my_typea
    val myTypeA: String = "",

    @Column(name = "my_type_b") // when @Column annotation is commented, column will be resulted in my_typeb
    val myTypeB: String = "",
)

I'm **expecting** that `myTypeA` and `myTypeB` will be resulted into `my_type_a` and `my_type_b`,
but **actual** values are `my_typea` and `my_typeb`

---
Regards,
Maksim
